// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: enums/card_rarity_type.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardRarityType
type CardRarityType int32

const (
	CardRarityType_CARD_RARITY_TYPE_UNSPECIFIED CardRarityType = 0
	CardRarityType_CARD_RARITY_TYPE_RARITY_1    CardRarityType = 1
	CardRarityType_CARD_RARITY_TYPE_RARITY_2    CardRarityType = 2
	CardRarityType_CARD_RARITY_TYPE_RARITY_3    CardRarityType = 3
)

// Enum value maps for CardRarityType.
var (
	CardRarityType_name = map[int32]string{
		0: "CARD_RARITY_TYPE_UNSPECIFIED",
		1: "CARD_RARITY_TYPE_RARITY_1",
		2: "CARD_RARITY_TYPE_RARITY_2",
		3: "CARD_RARITY_TYPE_RARITY_3",
	}
	CardRarityType_value = map[string]int32{
		"CARD_RARITY_TYPE_UNSPECIFIED": 0,
		"CARD_RARITY_TYPE_RARITY_1":    1,
		"CARD_RARITY_TYPE_RARITY_2":    2,
		"CARD_RARITY_TYPE_RARITY_3":    3,
	}
)

func (x CardRarityType) Enum() *CardRarityType {
	p := new(CardRarityType)
	*p = x
	return p
}

func (x CardRarityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardRarityType) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_card_rarity_type_proto_enumTypes[0].Descriptor()
}

func (CardRarityType) Type() protoreflect.EnumType {
	return &file_enums_card_rarity_type_proto_enumTypes[0]
}

func (x CardRarityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardRarityType.Descriptor instead.
func (CardRarityType) EnumDescriptor() ([]byte, []int) {
	return file_enums_card_rarity_type_proto_rawDescGZIP(), []int{0}
}

var File_enums_card_rarity_type_proto protoreflect.FileDescriptor

var file_enums_card_rarity_type_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x72, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2a, 0x8f, 0x01, 0x0a, 0x0e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x41, 0x52, 0x44,
	0x5f, 0x52, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x41,
	0x52, 0x44, 0x5f, 0x52, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52,
	0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x41, 0x52,
	0x44, 0x5f, 0x52, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x41,
	0x52, 0x49, 0x54, 0x59, 0x5f, 0x32, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x41, 0x52, 0x44,
	0x5f, 0x52, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x41, 0x52,
	0x49, 0x54, 0x59, 0x5f, 0x33, 0x10, 0x03, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6d, 0x61, 0x74, 0x6f, 0x30, 0x32, 0x30, 0x34,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x63, 0x61, 0x72, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enums_card_rarity_type_proto_rawDescOnce sync.Once
	file_enums_card_rarity_type_proto_rawDescData = file_enums_card_rarity_type_proto_rawDesc
)

func file_enums_card_rarity_type_proto_rawDescGZIP() []byte {
	file_enums_card_rarity_type_proto_rawDescOnce.Do(func() {
		file_enums_card_rarity_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_enums_card_rarity_type_proto_rawDescData)
	})
	return file_enums_card_rarity_type_proto_rawDescData
}

var file_enums_card_rarity_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_card_rarity_type_proto_goTypes = []any{
	(CardRarityType)(0), // 0: enums.CardRarityType
}
var file_enums_card_rarity_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_card_rarity_type_proto_init() }
func file_enums_card_rarity_type_proto_init() {
	if File_enums_card_rarity_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enums_card_rarity_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_card_rarity_type_proto_goTypes,
		DependencyIndexes: file_enums_card_rarity_type_proto_depIdxs,
		EnumInfos:         file_enums_card_rarity_type_proto_enumTypes,
	}.Build()
	File_enums_card_rarity_type_proto = out.File
	file_enums_card_rarity_type_proto_rawDesc = nil
	file_enums_card_rarity_type_proto_goTypes = nil
	file_enums_card_rarity_type_proto_depIdxs = nil
}
