output = "../../internal/domain/entity/master"
pkgname = "master"
no-tests = true

[mysql]
  dbname = "master"
  host = "localhost"
  port = 3306
  user = "root"
  pass = "root"
  sslmode = "false"
  blacklist = ["schema_migrations"]

[[types]]
  [types.match]
    type = "int"
  [types.replace]
    type = "int32"

[[types]]
  [types.match]
    type = "uint"
  [types.replace]
    type = "uint32"
